[build]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz"

[phases.setup]
nixPkgs = ["dotnet-sdk_8_0"]

[phases.build]
cmds = ["dotnet publish BotTelegram.csproj -c Release -r linux-x64 --self-contained true -o /app/publish"]

[start]
cmd = "/app/publish/BotTelegram"
